# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
  
jobs:
  build:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to build npm code
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to test code
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  analyze:
    # Use docker image for Node.js
    docker:
      - image: circleci/node:13.8.0
    # Add step to analyze vulnerabilities in the code
    steps:
      - checkout
      - run: npm audit
      
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "my_workflow"
  my_workflow:
    # Run the build, test and analyze jobs
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
           requires: [test]
